CREATE TABLE ziffapp.orders
(
    `mode` Int8,
    `order_id` Int64,
    `order_number` String,
    `country_code` FixedString(2),
    `status` Int8,
    `brand_id` Int8,
    `brand_name` Nullable(String),
    `customer_id` Int64,
    `fullname` String,
    `customer_hash` String,
    `phone_encrypted` String,
    `phone_prefix` Nullable(String),
    `fullname_encrypted` String,
    `customer_gender` String,
    `date_of_birth` String,
    `date_of_birth_year` String,
    `date_of_birth_month` String,
    `date_of_birth_day` String,
    `city_name` Nullable(String),
    `after_take_last_user_id` Nullable(Int64),
    `after_take_last_username` Nullable(Int64),
    `after_take_last_datetime` Nullable(DateTime),
    `created_at` DateTime,
    `network_group_id` Int64,
    `network_group_name` Nullable(String),
    `network_id` Int64,
    `network_name` Nullable(String),
    `network_print_name` Nullable(String),
    `offer_id` Int64,
    `offer_name` Nullable(String),
    `offer_product_id` Int64,
    `offer_product_name` Nullable(String),
    `click_id` String,
    `sub_1` Nullable(String),
    `sub_2` Nullable(String),
    `sub_3` Nullable(String),
    `sub_4` Nullable(String),
    `sub_5` Nullable(String),
    `url` Nullable(String),
    `date_of_planned_ship` Nullable(DateTime),
    `date_of_shipment` Nullable(DateTime),
    `date_of_refund` Nullable(DateTime),
    `date_of_return` Nullable(DateTime),
    `date_of_confirmed` Nullable(DateTime),
    `date_of_paid` Nullable(DateTime),
    `date_of_trash` Nullable(DateTime),
    `date_of_canceled` Nullable(DateTime),
    `date_of_call_again` Nullable(DateTime),
    `date_of_personal_call_again` Nullable(DateTime),
    `personal_call_again_note` Nullable(String),
    `revenue` Nullable(Decimal(12, 7)),
    `vat_rate` Nullable(Int8),
    `items_cost_in_eur` Nullable(Decimal(12, 7)),
    `items_cost_additional_in_eur` Nullable(Decimal(12, 7)),
    `shipping_cost_in_eur` Nullable(Decimal(12, 7)),
    `payout_cost_in_eur` Nullable(Decimal(12, 7)),
    `coupon_amount` Nullable(Decimal(12, 7)),
    `coupon_expire_days` Nullable(Int64),
    `coupon_expire_at_date` Nullable(DateTime),
    `delivery_id` Int64,
    `delivery_name` Nullable(String),
    `list_id` Int64,
    `list_name` Nullable(String),
    `confirm_to_cancel` Int8,
    `updated_at` DateTime DEFAULT now(),
    `is_mobile_phone` Int8,
    `customer_hash_int` UInt64 DEFAULT cityHash64(customer_hash),
    `profit` Decimal(18, 7) ALIAS round(if((status IN (4, 5, 7)), coalesce(revenue, 0), 0) - ((coalesce(shipping_cost_in_eur, 0) + coalesce(payout_cost_in_eur, 0)) + if((status IN (5, 7)), (coalesce(items_cost_in_eur, 0) + coalesce(items_cost_additional_in_eur, 0)) + ((coalesce(revenue, 0) / (1 + (coalesce(vat_rate, 0) / 100.))) * (coalesce(vat_rate, 0) / 100.)), 0)), 2),
    INDEX fullname_bf fullname TYPE tokenbf_v1(1024, 3, 0) GRANULARITY 1
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY order_id
SETTINGS min_age_to_force_merge_seconds = 30, index_granularity = 8192