CREATE VIEW ziffapp.views_orders_final
(
    `mode` Int8,
    `order_id` Int64,
    `order_number` String,
    `country_code` FixedString(2),
    `status` Int8,
    `brand_id` Int8,
    `brand_name` Nullable(String),
    `customer_id` Int64,
    `fullname` String,
    `customer_hash` String,
    `phone_encrypted` String,
    `phone_prefix` Nullable(String),
    `fullname_encrypted` String,
    `customer_gender` String,
    `date_of_birth` String,
    `date_of_birth_year` String,
    `date_of_birth_month` String,
    `date_of_birth_day` String,
    `city_name` Nullable(String),
    `after_take_last_user_id` Nullable(Int64),
    `after_take_last_username` Nullable(Int64),
    `after_take_last_datetime` Nullable(DateTime),
    `created_at` DateTime,
    `network_group_id` Int64,
    `network_group_name` Nullable(String),
    `network_id` Int64,
    `network_name` Nullable(String),
    `network_print_name` Nullable(String),
    `offer_id` Int64,
    `offer_name` Nullable(String),
    `offer_product_id` Int64,
    `offer_product_name` Nullable(String),
    `click_id` String,
    `sub_1` Nullable(String),
    `sub_2` Nullable(String),
    `sub_3` Nullable(String),
    `sub_4` Nullable(String),
    `sub_5` Nullable(String),
    `url` Nullable(String),
    `date_of_planned_ship` Nullable(DateTime),
    `date_of_shipment` Nullable(DateTime),
    `date_of_refund` Nullable(DateTime),
    `date_of_return` Nullable(DateTime),
    `date_of_confirmed` Nullable(DateTime),
    `date_of_paid` Nullable(DateTime),
    `revenue` Nullable(Decimal(12, 7)),
    `cost_per_item_euro` Nullable(Decimal(12, 7)),
    `cost_per_item_additional_euro` Nullable(Decimal(12, 7)),
    `quantity` Nullable(Decimal(12, 7)),
    `vat_rate` Nullable(Int8),
    `payout_in_eur` Nullable(Decimal(12, 7)),
    `shipping_price_in_eur` Nullable(Decimal(12, 7)),
    `coupon_amount` Nullable(Decimal(12, 7)),
    `coupon_expire_days` Nullable(Int64),
    `coupon_expire_at_date` Nullable(DateTime),
    `delivery_id` Int64,
    `delivery_name` Nullable(String),
    `list_id` Int64,
    `list_name` Nullable(String),
    `confirm_to_cancel` Int8,
    `updated_at` DateTime,
    `is_deleted` Int8,
    `is_unsubscribed` Int8,
    `customer_hash_int` UInt64,
    `statusText` String
)
AS SELECT
    o.*,
    multiIf(o.status = 1, 'Pending', o.status = 2, 'Take', o.status = 3, 'Call again', o.status = 4, 'Confirmed', o.status = 5, 'Shipped', o.status = 6, 'Returned', o.status = 7, 'Paid', o.status = 8, 'Trash', o.status = 9, 'Canceled', o.status = 10, 'Refunded', 'Unknown') AS statusText
FROM ziffapp.orders AS o
FINAL